language: python
python:
    - "3.6"
    - "2.7"
install:
    pip install -r requirements.txt

jobs:
    include:
        - stage: "Lint"
          python:
              - "3.6"
              - "2.7"
          script: python -m flake8
        - stage: "Test"
          python:
              - "3.6"
              - "2.7"
          script: pytest tests
