language: python
python:
    - "3.6"
    - "2.7"
install:
    pip install -r requirements.txt
script:
    python -m flake8
jobs:
    include: 
        - stage: test
          script:
              pytest tests
