language: python
python:
    - "3.6"
    - "2.7"
install:
    pip install -r requirements.txt


jobs:
    include:
        - stage: "Lint and Test"
          script: python -m flake8
          script: pytest tests
