language: python
python:
    - "3.6"
    - "2.7"
install:
    pip install -r requirements.txt
stages:
    - lint
    - test
jobs:
    include:
        - stage: lint
          name: "Checking flake8"
          script:
              python -m flake8
        - stage: test
          name: "Testing code"
          script:
              pytest tests
