language: python
python:
    - "3.6"
    - "2.7"
install:
    pip install -r requirements.txt
stages:
    - name: lint
      script:
          python -m flake8
    - name: test
      script:
          pytest tests
