language: python
jobs:
    include: 
        - stage: lint
          name: "Python 2.7 lint"
          python: "2.7"
          script: python -m flake8
          notifications:
              slack:
                  rooms:
                      - akhtyamovpavel:z3d9voquUsgMhRaNCUZr8Ag9
        - stage: lint
          name: "Python 3.6 lint"
          python: "3.6"
          script: python -m flake8
        - stage: test
          python: "2.7"
          name: "Python 2.7 tests"
          script: pytest tests
        - stage: test
          name: "Python 3.6 tests"
          python: "3.6"
          script: pytest tests
        - stage: notif
          name: "Notification send"
          install: skip
          script: skip
          notifications:
              slack: 'akhtyamovpavel:z3d9voquUsgMhRaNCUZr8Ag9'
notifications:
    slack: 'akhtyamovpavel:z3d9voquUsgMhRaNCUZr8Ag9'
stages:
    - lint
    - test
    - notif
