language: python
python:
    - "3.6"
    - "2.7"

jobs:
    include: 
        - stage: "Lint"
          python:
              - "3.6"
              - "2.7"
          install:
              pip install -r requirements.txt
          script:
              python -m flake8
        - stage: "Test"
          python:
              - "3.6"
              - "2.7"
          install:
              pip install -r requirements.txt
          script:
              pytest tests
