language: python
python:
    - "3.6"
    - "2.7"
install:
    pip install -r requirements.txt
jobs:
    stages:
        - lint
        - test
    include:
        - stage: lint
          name: "Checking flake8"
          script:
              flake8
        - stage: test
          name: "Testing code"
          script:
              pytest tests
